# Generated by Django 5.1.2 on 2024-11-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.CreateModel(
            name='TransferVariables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('shares', models.PositiveIntegerField()),
                ('start_date', models.CharField(max_length=300)),
                ('end_date', models.CharField(max_length=300)),
                ('permitted_uses', models.CharField(max_length=300)),
            ],
        ),
    ]
