# Generated by Django 5.1.2 on 2024-11-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfervariables',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='transfervariables',
            name='water_right',
        ),
        migrations.AlterField(
            model_name='transfervariables',
            name='end_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='transfervariables',
            name='start_date',
            field=models.CharField(max_length=300),
        ),
    ]
